import { Meta, StoryObj } from "@storybook/react";
import { fn } from "@storybook/test";
import { ChatScreenKeywords } from "../components/chatScreen/ChatScreenKeywords";

const ActionsData = {
  handleStartFresh: fn(),
  handleProceed: fn(),
};

const meta: Meta<typeof ChatScreenKeywords> = {
  title: "Native App/ChatScreen/ChatScreenKeywords",
  component: ChatScreenKeywords,
  parameters: {
    // Optional parameter to center the component in the Canvas. More info: https://storybook.js.org/docs/configure/story-layout
    layout: "centered",
  },
  // This component will have an automatically generated Autodocs entry: https://storybook.js.org/docs/writing-docs/autodocs
  tags: ["autodocs"],

  args: {
    ...ActionsData,
  },
  // More on argTypes: https://storybook.js.org/docs/api/argtypes
};

export default meta;

type Story = StoryObj<typeof ChatScreenKeywords>;

export const Default: Story = {
  args: {
    pageHeading: "Campagin on Sustainable Products",
    productCampaign: {
      description: "Sustainable Shoes",
      language: "English",
      country: "United States",
    },
    keywordsData: [
      {
        keyword: "sustainable shoes",
        monthlySearchVolume: "1000",
        avgMonthlySearches: "12000",
        cpc: "$1.00",
        competition: "Low",
        lowBid: "$0.50",
        highBid: "$1.50",
        key: "1",
      },
      {
        keyword: "eco-friendly footwear",
        monthlySearchVolume: "1500",
        avgMonthlySearches: "18000",
        cpc: "$1.20",
        competition: "Medium",
        lowBid: "$0.70",
        highBid: "$2.00",
        key: "2",
      },
      {
        keyword: "recycled material shoes",
        monthlySearchVolume: "800",
        avgMonthlySearches: "10000",
        cpc: "$0.90",
        competition: "Low",
        lowBid: "$0.40",
        highBid: "$1.30",
        key: "3",
      },
      {
        keyword: "vegan shoes",
        monthlySearchVolume: "2000",
        avgMonthlySearches: "25000",
        cpc: "$1.50",
        competition: "High",
        lowBid: "$1.00",
        highBid: "$2.50",
        key: "4",
      },
      {
        keyword: "organic shoes",
        monthlySearchVolume: "1200",
        avgMonthlySearches: "14000",
        cpc: "$1.10",
        competition: "Medium",
        lowBid: "$0.60",
        highBid: "$1.80",
        key: "5",
      },
      {
        keyword: "carbon neutral shoes",
        monthlySearchVolume: "900",
        avgMonthlySearches: "11000",
        cpc: "$1.00",
        competition: "Low",
        lowBid: "$0.50",
        highBid: "$1.50",
        key: "6",
      },
      {
        keyword: "sustainable sneakers",
        monthlySearchVolume: "1300",
        avgMonthlySearches: "15000",
        cpc: "$1.25",
        competition: "Medium",
        lowBid: "$0.75",
        highBid: "$2.10",
        key: "7",
      },
      {
        keyword: "ethical shoes",
        monthlySearchVolume: "1000",
        avgMonthlySearches: "12000",
        cpc: "$1.00",
        competition: "Low",
        lowBid: "$0.50",
        highBid: "$1.50",
        key: "8",
      },
      {
        keyword: "biodegradable shoes",
        monthlySearchVolume: "700",
        avgMonthlySearches: "9000",
        cpc: "$0.85",
        competition: "Low",
        lowBid: "$0.40",
        highBid: "$1.20",
        key: "9",
      },
      {
        keyword: "sustainable fashion",
        monthlySearchVolume: "2200",
        avgMonthlySearches: "27000",
        cpc: "$1.60",
        competition: "High",
        lowBid: "$1.20",
        highBid: "$3.00",
        key: "",
      },
      {
        keyword: "eco-conscious shoes",
        monthlySearchVolume: "950",
        avgMonthlySearches: "11000",
        cpc: "$1.05",
        competition: "Medium",
        lowBid: "$0.55",
        highBid: "$1.70",
        key: "10",
      },
      {
        keyword: "fair trade shoes",
        monthlySearchVolume: "1100",
        avgMonthlySearches: "13000",
        cpc: "$1.15",
        competition: "Medium",
        lowBid: "$0.65",
        highBid: "$1.90",
        key: "11",
      },
      {
        keyword: "renewable material shoes",
        monthlySearchVolume: "600",
        avgMonthlySearches: "8000",
        cpc: "$0.75",
        competition: "Low",
        lowBid: "$0.35",
        highBid: "$1.10",
        key: "12",
      },
      {
        keyword: "zero waste shoes",
        monthlySearchVolume: "500",
        avgMonthlySearches: "7000",
        cpc: "$0.70",
        competition: "Low",
        lowBid: "$0.30",
        highBid: "$1.00",
        key: "13",
      },
      {
        keyword: "upcycled shoes",
        monthlySearchVolume: "850",
        avgMonthlySearches: "10000",
        cpc: "$0.95",
        competition: "Low",
        lowBid: "$0.45",
        highBid: "$1.40",
        key: "14",
      },
      {
        keyword: "low carbon footprint shoes",
        monthlySearchVolume: "750",
        avgMonthlySearches: "9000",
        cpc: "$0.90",
        competition: "Low",
        lowBid: "$0.40",
        highBid: "$1.30",
        key: "15",
      },
      {
        keyword: "sustainable running shoes",
        monthlySearchVolume: "1600",
        avgMonthlySearches: "20000",
        cpc: "$1.30",
        competition: "Medium",
        lowBid: "$0.80",
        highBid: "$2.20",
        key: "16",
      },
      {
        keyword: "eco-friendly sneakers",
        monthlySearchVolume: "1400",
        avgMonthlySearches: "17000",
        cpc: "$1.20",
        competition: "Medium",
        lowBid: "$0.70",
        highBid: "$2.00",
        key: "17",
      },
      {
        keyword: "green shoes",
        monthlySearchVolume: "1200",
        avgMonthlySearches: "15000",
        cpc: "$1.10",
        competition: "Medium",
        lowBid: "$0.60",
        highBid: "$1.80",
        key: "18",
      },
      {
        keyword: "plant-based shoes",
        monthlySearchVolume: "600",
        avgMonthlySearches: "8000",
        cpc: "$0.75",
        competition: "Low",
        lowBid: "$0.35",
        highBid: "$1.10",
        key: "19",
      },
    ],
  },
};
